name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Backend
        run: |
          curl -L --fail https://hunterai-1-6wbc.onrender.com/health
